# Generated by Django 3.2.2 on 2021-07-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2021-07-01')),
                ('due_date', models.DateField(default='2021-07-01')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
